//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInfo()
        {
            this.Students_Subjects = new HashSet<Students_Subjects>();
        }
    
        public int StudentId { get; set; }
        public string StuNumber { get; set; }
        public string Name { get; set; }
        public int SpecialtyId { get; set; }
        public int ClassId { get; set; }
        public sbyte IsDel { get; set; }
    
        public virtual ClassInfo ClassInfo { get; set; }
        public virtual Specialty Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students_Subjects> Students_Subjects { get; set; }
    }
}
