//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_Subjects
    {
        public int Stu_SubId { get; set; }
        public int StuId { get; set; }
        public int SubId { get; set; }
        public sbyte IsPass { get; set; }
        public sbyte IsDel { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
