//------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Repository
{
    using System;
    public partial interface DBSession
    {
        ClassInfoDAL  ClassInfoDAL
    	{
    		get;
    	}
        CourseTypeDAL  CourseTypeDAL
    	{
    		get;
    	}
        SpecialtyDAL  SpecialtyDAL
    	{
    		get;
    	}
        StudentInfoDAL  StudentInfoDAL
    	{
    		get;
    	}
        Students_SubjectsDAL  Students_SubjectsDAL
    	{
    		get;
    	}
        SubjectsDAL  SubjectsDAL
    	{
    		get;
    	}
        UserCategoryDAL  UserCategoryDAL
    	{
    		get;
    	}
        UserInfoDAL  UserInfoDAL
    	{
    		get;
    	}
        Subject_CuorseDAL  Subject_CuorseDAL
    	{
    		get;
    	}
        Teacher_SubjectDAL  Teacher_SubjectDAL
    	{
    		get;
    	}
        TeacherInfoDAL  TeacherInfoDAL
    	{
    		get;
    	}
    }
}
