//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_CuorseBLL:BaseService<Models.Subject_Cuorse>,IService.ISubject_CuorseBLL
    {
    	IRepository.ISubject_CuorseDAL dal =null; 
    	public override void SetRepository(out IRepository.IBaseRepository<Models.Subject_Cuorse> baseRepository)
            {
                dal= base.DBSession.Subject_CuorseDAL;
                baseRepository = dal as IRepository.IBaseRepository<Models.Subject_Cuorse>;
            }
    }
}
