//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherInfoBLL:BaseService<Models.TeacherInfo>,IService.ITeacherInfoBLL
    {
    	IRepository.ITeacherInfoDAL dal =null; 
    	public override void SetRepository(out IRepository.IBaseRepository<Models.TeacherInfo> baseRepository)
            {
                dal= base.DBSession.TeacherInfoDAL;
                baseRepository = dal as IRepository.IBaseRepository<Models.TeacherInfo>;
            }
    }
}
