//------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.IRepository
{
    using System;
    public partial interface IDBSession
    {
        IClassInfoDAL  ClassInfoDAL
    	{
    		get;
    	}
        ICourseTypeDAL  CourseTypeDAL
    	{
    		get;
    	}
        ISpecialtyDAL  SpecialtyDAL
    	{
    		get;
    	}
        IStudentInfoDAL  StudentInfoDAL
    	{
    		get;
    	}
        IStudents_SubjectsDAL  Students_SubjectsDAL
    	{
    		get;
    	}
        ISubjectsDAL  SubjectsDAL
    	{
    		get;
    	}
        IUserCategoryDAL  UserCategoryDAL
    	{
    		get;
    	}
        IUserInfoDAL  UserInfoDAL
    	{
    		get;
    	}
        ISubject_CuorseDAL  Subject_CuorseDAL
    	{
    		get;
    	}
        ITeacher_SubjectDAL  Teacher_SubjectDAL
    	{
    		get;
    	}
        ITeacherInfoDAL  TeacherInfoDAL
    	{
    		get;
    	}
    }
}
