//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Models
{
	public partial class Students_Subjects
	{
		public Students_Subjects ToPOCO(){
			return new Students_Subjects(){
				Stu_SubId=this.Stu_SubId,
				StuId=this.StuId,
				SubId=this.SubId,
				IsPass=this.IsPass,
				IsDel=this.IsDel,
				};
		}
		}
}
