//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Models
{
	public partial class StudentInfo
	{
		public StudentInfo ToPOCO(){
			return new StudentInfo(){
				StudentId=this.StudentId,
				StuNumber=this.StuNumber,
				Name=this.Name,
				SpecialtyId=this.SpecialtyId,
				ClassId=this.ClassId,
				IsDel=this.IsDel,
				};
		}
		}
}
