//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.Models
{
	public partial class UserInfo
	{
		public UserInfo ToPOCO(){
			return new UserInfo(){
				UserId=this.UserId,
				UserCategoryId=this.UserCategoryId,
				Name=this.Name,
				UserName=this.UserName,
				UserPwd=this.UserPwd,
				AddTime=this.AddTime,
				LoginTime=this.LoginTime,
				IsDel=this.IsDel,
				};
		}
		}
}
