//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.IRepository
{
using System;
using System.Collections.Generic;

public partial class Subjects
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Subjects()
    {
        this.Students_Subjects = new HashSet<Students_Subjects>();
        this.Subject_Cuorse = new HashSet<Subject_Cuorse>();
        this.Teacher_Subject = new HashSet<Teacher_Subject>();
    }

    public int SubjectId { get; set; }
    public string SubjectName { get; set; }
    public int CourseTypeId { get; set; }
    public sbyte IsDel { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Students_Subjects> Students_Subjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Subject_Cuorse> Subject_Cuorse { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Teacher_Subject> Teacher_Subject { get; set; }
}
}
