//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.IRepository
{
using System;
using System.Collections.Generic;

public partial class Subject_Cuorse
{
    public int Id { get; set; }
    public int SubId { get; set; }
    public int CourseId { get; set; }
    public sbyte IsDel { get; set; }

    public virtual CourseType CourseType { get; set; }
    public virtual Subjects Subjects { get; set; }
}
}
