//------------------------------------------------------------------------------
// <auto-generated>
// 业务仓储，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.IService
{
    using System;
    public partial interface IServiceSession
    {
        IClassInfoBLL  ClassInfo
    	{
    		get;
    	}
        ICourseTypeBLL  CourseType
    	{
    		get;
    	}
        ISpecialtyBLL  Specialty
    	{
    		get;
    	}
        IStudentInfoBLL  StudentInfo
    	{
    		get;
    	}
        IStudents_SubjectsBLL  Students_Subjects
    	{
    		get;
    	}
        ISubjectsBLL  Subjects
    	{
    		get;
    	}
        IUserCategoryBLL  UserCategory
    	{
    		get;
    	}
        IUserInfoBLL  UserInfo
    	{
    		get;
    	}
        ISubject_CuorseBLL  Subject_Cuorse
    	{
    		get;
    	}
        ITeacher_SubjectBLL  Teacher_Subject
    	{
    		get;
    	}
        ITeacherInfoBLL  TeacherInfo
    	{
    		get;
    	}
    }
}
