//------------------------------------------------------------------------------
// <auto-generated>
// 业务仓储，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJ.IService
{
    using System;
    public partial interface IServiceSession
    {
        IClassInfoBLL  ClassInfoBLL
    	{
    		get;
    	}
        ICourseTypeBLL  CourseTypeBLL
    	{
    		get;
    	}
        ISpecialtyBLL  SpecialtyBLL
    	{
    		get;
    	}
        IStudentInfoBLL  StudentInfoBLL
    	{
    		get;
    	}
        IStudents_SubjectsBLL  Students_SubjectsBLL
    	{
    		get;
    	}
        ISubjectsBLL  SubjectsBLL
    	{
    		get;
    	}
        IUserCategoryBLL  UserCategoryBLL
    	{
    		get;
    	}
        IUserInfoBLL  UserInfoBLL
    	{
    		get;
    	}
        ISubject_CuorseBLL  Subject_CuorseBLL
    	{
    		get;
    	}
        ITeacher_SubjectBLL  Teacher_SubjectBLL
    	{
    		get;
    	}
        ITeacherInfoBLL  TeacherInfoBLL
    	{
    		get;
    	}
    }
}
